version: '1.0'
services:
  mysql:
    image: mysql:8.0.33
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'db_baste'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'pass'
    ports:
      - '8000:8000'
    volumes:
      - ./mysql-data:/var/lib/mysql
